name: Publish Docs

# Manually triggered
on:
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - uses: reitzig/actions-asciidoctor@v2.0.2
        with:
          version: 2.0.23

      - uses: actions/checkout@v4        

      - run: asciidoctor 'samples/extensions/tensor_and_data_graph/**/*.adoc'
      - run: |
          mkdir -p staging/
          shopt -s globstar
          # As well as the HTML files, copy other files that the docs link to (e.g. image files and shader files)
          cp -r --parents samples/extensions/tensor_and_data_graph/ shaders/tensor_and_data_graph/ staging/

      # Redirect the default /index.html page to our tensor_and_data_graph readme page, so we don't need to use the full link when sharing it
      - name: Create redirecting index.html
        run: |
          cat > staging/index.html <<EOF
          <!DOCTYPE html>
          <html>
          <head>
            <meta http-equiv="refresh" content="0; url=samples/extensions/tensor_and_data_graph/README.html">
            <title>Redirecting...</title>
          </head>
          <body>
            <p>If you are not redirected, <a href="samples/extensions/tensor_and_data_graph/README.html">click here</a>.</p>
          </body>
          </html>
          EOF

      - name: Upload HTML files as artifact
        id: upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: staging/

  publish:
    runs-on: ubuntu-latest
    needs: build-docs
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
